AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - SQS to Lambda

Resources:
  # Define the SQS queue
  BarrySqs:
    Type: AWS::SQS::Queue

  # Define the consumer Lambda function
  BarrySqsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: lambda.handler
      Runtime: nodejs12.x
      Timeout: 3
      MemorySize: 128
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BarrySqs.Arn
            BatchSize: 10
Outputs:
  BarrySqsFunction:
    Description: BarrySqsFunction function name
    Value: !Ref BarrySqsFunction
  
  SQSqueueName:
    Description: SNS queue name
    Value: !GetAtt BarrySqs.QueueName

  SQSqueueARN:
    Description: SQS queue ARN
    Value: !GetAtt BarrySqs.Arn

  SQSqueueURL:
    Description: SQS queue URL
    Value: !Ref BarrySqs